worker_processes 8;
worker_rlimit_nofile 1048576;

events {
    worker_connections 65535;
    use io_uring;
}

http {
    access_log off;
    tcp_nopush on;
    tcp_nodelay on;

    proxy_http_version 1.1;
    proxy_set_header Connection "keep-alive";

    upstream backend {
        server 127.0.0.1:3005;
        keepalive 255;
    }


    server {
        listen 8080 reuseport;
        server_name site1.local;
        root ./www/vhost1/;
        index default.html custom.htm index_.html index.html;

        shiny_xdp on;
        
        location /api/ {
            proxy_pass http://backend;
        }

        location /api_sock/ {
            proxy_pass unix:./conf.d/node.sock;
        }
    }

    server {
        listen 8081 reuseport;
        #server_name site2.local;
        root ./www/vhost2/;

        shiny_xdp on;

        location /api/ {
            proxy_pass http://backend;
        }
    }
}
